# Generated by Django 4.2.2 on 2023-07-31 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="quesOne",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ans1", models.CharField(blank=True, max_length=10, null=True)),
                ("ans2", models.CharField(blank=True, max_length=10, null=True)),
                ("ans3", models.CharField(blank=True, max_length=10, null=True)),
                ("ans4", models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
