# Generated by Django 4.2.3 on 2023-08-02 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="quesFive",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ans1", models.CharField(blank=True, max_length=10, null=True)),
                ("ans2", models.CharField(blank=True, max_length=10, null=True)),
                ("ans3", models.CharField(blank=True, max_length=10, null=True)),
                ("ans4", models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="quesFour",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ans1", models.CharField(blank=True, max_length=10, null=True)),
                ("ans2", models.CharField(blank=True, max_length=10, null=True)),
                ("ans3", models.CharField(blank=True, max_length=10, null=True)),
                ("ans4", models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="quesThree",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ans1", models.CharField(blank=True, max_length=10, null=True)),
                ("ans2", models.CharField(blank=True, max_length=10, null=True)),
                ("ans3", models.CharField(blank=True, max_length=10, null=True)),
                ("ans4", models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="quesTwo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ans1", models.CharField(blank=True, max_length=10, null=True)),
                ("ans2", models.CharField(blank=True, max_length=10, null=True)),
                ("ans3", models.CharField(blank=True, max_length=10, null=True)),
                ("ans4", models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
